plugins {
    `java-library`
    `maven-publish`
    id("net.neoforged.gradle.userdev") version "7.0.192"
    // Adds the Kotlin Gradle plugin
    kotlin("jvm") version "2.1.21"
    // OPTIONAL Kotlin Serialization plugin
    kotlin("plugin.serialization") version "2.1.21"
    // shadow
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

tasks.wrapper {
    // Define wrapper values here so as to not have to always do so when updating gradlew.properties.
    // Switching this to Wrapper.DistributionType.ALL will download the full gradle sources that comes with
    // documentation attached on cursor hover of gradle classes and methods. However, this comes with increased
    // file size for Gradle. If you do switch this to ALL, run the Gradle wrapper task twice afterwards.
    // (Verify by checking gradle/wrapper/gradle-wrapper.properties to see if distributionUrl now points to `-all`)
    distributionType = Wrapper.DistributionType.BIN
}

version = project.properties["mod_version"].toString()
group = project.properties["mod_group_id"].toString()

repositories {
    // Add here additional repositories if required by some of the dependencies below.
    maven {
        name = "Kotlin for Forge"
        url = uri("https://thedarkcolour.github.io/KotlinForForge/")
    }
    maven {
        name = "NeoForged"
        url = uri("https://maven.neoforged.net/releases")
    }
    maven {
        name = "Forge"
        url = uri("https://maven.minecraftforge.net")
    }
}

base {
    archivesName = project.properties["mod_id"].toString()
}

// Mojang ships Java 21 to end users in 1.21.1, so mods should target Java 21.
java.toolchain.languageVersion.set(JavaLanguageVersion.of(21))

//minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')
//minecraft.accessTransformers.entry public net.minecraft.client.Minecraft textureManager # textureManager

// Default run configurations.
// These can be tweaked, removed, or duplicated as needed.
runs {
    // applies to all the run configs below
    configureEach {
        // Recommended logging data for a userdev environment
        // The markers can be added/remove as needed separated by commas.
        // "SCAN": For mods scan.
        // "REGISTRIES": For firing of registry events.
        // "REGISTRYDUMP": For getting the contents of all registries.
        systemProperty("forge.logging.markers", "REGISTRIES")

        // Recommended logging level for the console
        // You can set various levels here.
        // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
        systemProperty("forge.logging.console.level", "debug")

        modSource(sourceSets["main"])
    }

    create("client") {
        client()
        // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
        systemProperty("neoforge.enabledGameTestNamespaces", project.properties["mod_id"].toString())
    }

    create("server") {
        server()
        systemProperty("neoforge.enabledGameTestNamespaces", project.properties["mod_id"].toString())
        programArgument("--nogui")
    }

    // This run config launches GameTestServer and runs all registered gametests, then exits.
    // By default, the server will crash when no gametests are provided.
    // The gametest system is also enabled by default for other run configs under the /test command.
    create("gameTestServer") {
        gameTest()
        systemProperty("neoforge.enabledGameTestNamespaces", project.properties["mod_id"].toString())
    }

    create("data") {
        dataGenerator()
        // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
        // workingDirectory.set(project.file("run-data"))

        // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
        programArguments.addAll(
            "--mod",
            project.properties["mod_id"].toString(),
            "--all",
            "--output",
            file("src/generated/resources/").absolutePath,
            "--existing",
            file("src/main/resources/").absolutePath
        )
    }
}

// Include resources generated by data generators.
sourceSets.main.get().resources.srcDir("src/generated/resources")

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.get().extendsFrom(configurations["localRuntime"])
    create("shadowCommon")
}

dependencies {
    // Specify the version of Minecraft to use.
    // Depending on the plugin applied there are several options. We will assume you applied the userdev plugin as shown above.
    // The group for userdev is net.neoforged, the module name is neoforge, and the version is the same as the neoforge version.
    // You can however also use the vanilla plugin (net.neoforged.gradle.vanilla) to use a version of Minecraft without the neoforge loader.
    // And its provides the option to then use net.minecraft as the group, and one of; client, server or joined as the module name, plus the game version as version.
    // For all intends and purposes: You can treat this dependency as if it is a normal library you would use.
    implementation("net.neoforged:neoforge:${project.properties["neo_version"]}")

    // Example optional mod dependency with JEI
    // The JEI API is declared for compile time use, while the full JEI artifact is used at runtime
    // compileOnly("mezz.jei:jei-${mc_version}-common-api:${jei_version}")
    // compileOnly("mezz.jei:jei-${mc_version}-neoforge-api:${jei_version}")
    // We add the full version to localRuntime, not runtimeOnly, so that we do not publish a dependency on it
    // localRuntime("mezz.jei:jei-${mc_version}-neoforge:${jei_version}")

    // Example mod dependency using a mod jar from ./libs with a flat dir repository
    // This maps to ./libs/coolmod-${mc_version}-${coolmod_version}.jar
    // The group id is ignored when searching -- in this case, it is "blank"
    // implementation("blank:coolmod-${mc_version}:${coolmod_version}")

    // Example mod dependency using a file as dependency
    // implementation(files("libs/coolmod-${mc_version}-${coolmod_version}.jar"))

    // Example project dependency using a sister or child project:
    // implementation(project(":myproject"))

    // For more info:
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html

    // KFF
    implementation("thedarkcolour:kotlinforforge-neoforge:5.9.0")
    implementation("com.github.glitchfiend:TerraBlender-neoforge:1.21.1-4.1.0.8")
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
// When "copyIdeResources" is enabled, this will also run before the game launches in IDE environments.
// See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
tasks.withType<ProcessResources> {
    val replaceProperties = mapOf(
        "minecraft_version" to project.properties["minecraft_version"],
        "minecraft_version_range" to project.properties["minecraft_version_range"],
        "neo_version" to project.properties["neo_version"],
        "loader_version_range" to project.properties["loader_version_range"],
        "mod_id" to project.properties["mod_id"],
        "mod_name" to project.properties["mod_name"],
        "mod_license" to project.properties["mod_license"],
        "mod_version" to project.properties["mod_version"],
        "mod_authors" to project.properties["mod_authors"],
        "mod_description" to project.properties["mod_description"]
    )
    inputs.properties(replaceProperties)

    filesMatching("META-INF/neoforge.mods.toml") {
        expand(replaceProperties)
    }
}

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri("file://${project.projectDir}/repo")
        }
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8" // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}

tasks.shadowJar {
    configurations = listOf(project.configurations["shadowCommon"])
    archiveFileName.set(
        "${project.properties["mod_id"]}-" +
                "${project.properties["minecraft_version"]}-" +
                "${project.properties["mod_version"]}-" +
                "neoforge.jar")
}