package sokeriaaa.candyworld.registry

import net.minecraft.world.food.FoodProperties

object ModFoods {
    val BUTTER = FoodProperties.Builder()
        .nutrition(1)
        .saturationModifier(1.0f)
        .build()
    val COTTON_CANDY = FoodProperties.Builder()
        .nutrition(4)
        .saturationModifier(0.5f)
        .build()
    val COTTON_CANDY_TOOL = FoodProperties.Builder()
        .nutrition(1)
        .saturationModifier(0.6f)
        .build()
    val WAFER_STICK = FoodProperties.Builder()
        .nutrition(5)
        .saturationModifier(0.6f)
        .build()
    val SUGAR_ROCK = FoodProperties.Builder()
        .nutrition(4)
        .saturationModifier(0.2f)
        .build()
    val CANDY_CANE = FoodProperties.Builder()
        .nutrition(5)
        .saturationModifier(0.6f)
        .build()
    val BROWNIE = FoodProperties.Builder()
        .nutrition(4)
        .saturationModifier(0.5f)
        .build()
    val CHOCOLATE_BAR = FoodProperties.Builder()
        .nutrition(6)
        .saturationModifier(0.6f)
        .build()
    val CHOCOLATE_EGG = FoodProperties.Builder()
        .nutrition(7)
        .saturationModifier(0.8f)
        .build()
    val CHOCOLATE_TOOL = FoodProperties.Builder()
        .nutrition(6)
        .saturationModifier(0.6f)
        .build()
    val GUMMY = FoodProperties.Builder()
        .nutrition(4)
        .saturationModifier(0.6f)
        .build()
    val GUMMY_WORM = FoodProperties.Builder()
        .nutrition(6)
        .saturationModifier(1.0f)
        .build()
    val TELEPORTER = FoodProperties.Builder()
        .nutrition(1)
        .saturationModifier(1.0f)
        .alwaysEdible()
        .build()
}
