package sokeriaaa.candyworld.platform.neoforge.datagen.providers.client

import net.minecraft.data.PackOutput
import net.minecraft.world.level.material.FlowingFluid
import net.neoforged.neoforge.common.data.LanguageProvider
import sokeriaaa.candyworld.CandyWorld
import sokeriaaa.candyworld.blocks.fluid.ModFluids
import sokeriaaa.candyworld.registry.ModBlocks
import sokeriaaa.candyworld.registry.ModEntities
import sokeriaaa.candyworld.registry.ModItems
import sokeriaaa.candyworld.registry.RegistryObject

class CandyLanguage(
    output: PackOutput,
) : LanguageProvider(output, CandyWorld.MOD_ID, "en_us") {
    override fun addTranslations() {
        this.addBlock({ ModBlocks.CANDY_GRASS_BLOCK.value }, "Cotton Candy Grass")
        this.addBlock({ ModBlocks.CHOCOLATE_COVERED_WHITE_BROWNIE.value }, "Chocolate Covered White Brownie")
        this.addBlock({ ModBlocks.DARK_CANDY_GRASS_BLOCK.value }, "Covered Dark Brownie")
        this.addBlock({ ModBlocks.COTTON_CANDY_PLANT.value }, "Cotton Candy Plant")
        this.addBlock({ ModBlocks.COTTON_CANDY_SAPLING.value }, "Cotton Candy Sapling")
        this.addBlock({ ModBlocks.COTTON_CANDY_LEAVES.value }, "Cotton Candy Leaves")
        this.addBlock({ ModBlocks.COTTON_CANDY_BUSH.value }, "Cotton Candy Bush")
        this.addBlock({ ModBlocks.WHITE_CANDY_CANE_BLOCK.value }, "White Candy Cane Block")
        this.addBlock({ ModBlocks.RED_CANDY_CANE_BLOCK.value }, "Red Candy Cane Block")
        this.addBlock({ ModBlocks.GREEN_CANDY_CANE_BLOCK.value }, "Green Candy Cane Block")
        this.addBlock({ ModBlocks.WHITE_RED_CANDY_CANE_BLOCK.value }, "White-Red Candy Cane Block")
        this.addBlock({ ModBlocks.WHITE_GREEN_CANDY_CANE_BLOCK.value }, "White-Green Candy Cane Block")
        this.addBlock({ ModBlocks.RED_GREEN_CANDY_CANE_BLOCK.value }, "Red-Green Candy Cane Block")
        this.addBlock({ ModBlocks.MILK_BROWNIE_BLOCK.value }, "Milk Brownie Block")
        this.addBlock({ ModBlocks.WHITE_BROWNIE_BLOCK.value }, "White Brownie Block")
        this.addBlock({ ModBlocks.DARK_BROWNIE_BLOCK.value }, "Dark Brownie Block")
        this.addBlock({ ModBlocks.MILK_CHOCOLATE_LEAVES.value }, "Milk Chocolate Leaves")
        this.addBlock({ ModBlocks.WHITE_CHOCOLATE_LEAVES.value }, "White Chocolate Leaves")
        this.addBlock({ ModBlocks.DARK_CHOCOLATE_LEAVES.value }, "Dark Chocolate Leaves")
        this.addBlock({ ModBlocks.MILK_CHOCOLATE_BLOCK.value }, "Milk Chocolate Block")
        this.addBlock({ ModBlocks.WHITE_CHOCOLATE_BLOCK.value }, "White Chocolate Block")
        this.addBlock({ ModBlocks.DARK_CHOCOLATE_BLOCK.value }, "Dark Chocolate Block")
        this.addBlock({ ModBlocks.MILK_CHOCOLATE_BAR_BLOCK.value }, "Milk Chocolate Bar")
        this.addBlock({ ModBlocks.WHITE_CHOCOLATE_BAR_BLOCK.value }, "White Chocolate Bar")
        this.addBlock({ ModBlocks.DARK_CHOCOLATE_BAR_BLOCK.value }, "Dark Chocolate Bar")
        this.addBlock({ ModBlocks.MILK_CHOCOLATE_BRICK.value }, "Milk Chocolate Bricks")
        this.addBlock({ ModBlocks.WHITE_CHOCOLATE_BRICK.value }, "White Chocolate Bricks")
        this.addBlock({ ModBlocks.DARK_CHOCOLATE_BRICK.value }, "Dark Chocolate Bricks")
        this.addBlock({ ModBlocks.WAFER_STICK_BLOCK.value }, "Wafer Stick Block")
        this.addBlock({ ModBlocks.CHOCOLATE_SAPLING.value }, "Chocolate Tree Sapling")
        this.addBlock({ ModBlocks.MILK_CHOCOLATE_MUSHROOM.value }, "Milk Chocolate Mushrooms")
        this.addBlock({ ModBlocks.WHITE_CHOCOLATE_MUSHROOM.value }, "White Chocolate Mushrooms")
        this.addBlock({ ModBlocks.DARK_CHOCOLATE_MUSHROOM.value }, "Dark Chocolate Mushrooms")
        this.addBlock({ ModBlocks.CRYSTALLIZED_SUGAR_COOKIE_ORE.value }, "Crystallized Sugar Cookie Ore")
        this.addBlock({ ModBlocks.COOKIE_ORE.value }, "Cookie Ore")
        this.addBlock({ ModBlocks.CRYSTALLIZED_SUGAR.value }, "Crystallized Sugar")
        this.addBlock({ ModBlocks.SUGAR_SAND.value }, "Sugar")
        this.addBlock({ ModBlocks.RED_GUMMY_BLOCK.value }, "Red Gummy Block")
        this.addBlock({ ModBlocks.ORANGE_GUMMY_BLOCK.value }, "Orange Gummy Block")
        this.addBlock({ ModBlocks.YELLOW_GUMMY_BLOCK.value }, "Yellow Gummy Block")
        this.addBlock({ ModBlocks.WHITE_GUMMY_BLOCK.value }, "White Gummy Block")
        this.addBlock({ ModBlocks.GREEN_GUMMY_BLOCK.value }, "Green Gummy Block")
        this.addBlock({ ModBlocks.RED_HARDENED_GUMMY_BLOCK.value }, "Red Solid Gummy Block")
        this.addBlock({ ModBlocks.ORANGE_HARDENED_GUMMY_BLOCK.value }, "Orange Solid Gummy Block")
        this.addBlock({ ModBlocks.YELLOW_HARDENED_GUMMY_BLOCK.value }, "Yellow Solid Gummy Block")
        this.addBlock({ ModBlocks.WHITE_HARDENED_GUMMY_BLOCK.value }, "White Solid Gummy Block")
        this.addBlock({ ModBlocks.GREEN_HARDENED_GUMMY_BLOCK.value }, "Green Solid Gummy Block")
        this.addBlock({ ModBlocks.RED_GUMMY_WORM_BLOCK.value }, "Red Gummy Worm Block")
        this.addBlock({ ModBlocks.ORANGE_GUMMY_WORM_BLOCK.value }, "Orange Gummy Worm Block")
        this.addBlock({ ModBlocks.YELLOW_GUMMY_WORM_BLOCK.value }, "Yellow Gummy Worm Block")
        this.addBlock({ ModBlocks.WHITE_GUMMY_WORM_BLOCK.value }, "White Gummy Worm Block")
        this.addBlock({ ModBlocks.GREEN_GUMMY_WORM_BLOCK.value }, "Green Gummy Worm Block")
        this.addBlock({ ModBlocks.TELEPORTER_ORE.value }, "Magic Candy Ore")
        this.addBlock({ ModBlocks.WHITE_CANDY_CANE_WORKBENCH.value }, "White Candy Cane Workbench")
        this.addBlock({ ModBlocks.RED_CANDY_CANE_WORKBENCH.value }, "Red Candy Cane Workbench")
        this.addBlock({ ModBlocks.GREEN_CANDY_CANE_WORKBENCH.value }, "Green Candy Cane Workbench")
        this.addBlock({ ModBlocks.WHITE_RED_CANDY_CANE_WORKBENCH.value }, "White-Red Candy Cane Workbench")
        this.addBlock({ ModBlocks.WHITE_GREEN_CANDY_CANE_WORKBENCH.value }, "White-Green Candy Cane Workbench")
        this.addBlock({ ModBlocks.RED_GREEN_CANDY_CANE_WORKBENCH.value }, "Red-Green Candy Cane Workbench")
        this.addBlock({ ModBlocks.MILK_CHOCOLATE_WORKBENCH.value }, "Milk Chocolate Workbench")
        this.addBlock({ ModBlocks.DARK_CHOCOLATE_WORKBENCH.value }, "Dark Chocolate Workbench")
        this.addBlock({ ModBlocks.WHITE_CHOCOLATE_WORKBENCH.value }, "White Chocolate Workbench")
        this.addBlock({ ModBlocks.RED_GUMMY_WORKBENCH.value }, "Red Gummy Workbench")
        this.addBlock({ ModBlocks.ORANGE_GUMMY_WORKBENCH.value }, "Orange Gummy Workbench")
        this.addBlock({ ModBlocks.YELLOW_GUMMY_WORKBENCH.value }, "Yellow Gummy Workbench")
        this.addBlock({ ModBlocks.WHITE_GUMMY_WORKBENCH.value }, "White Gummy Workbench")
        this.addBlock({ ModBlocks.GREEN_GUMMY_WORKBENCH.value }, "Green Gummy Workbench")

        this.addItem({ ModItems.COTTON_CANDY.value }, "Cotton Candy")
        this.addItem({ ModItems.BUTTER.value }, "Butter")
        this.addItem({ ModItems.WHITE_CANDY_CANE.value }, "White Candy Cane")
        this.addItem({ ModItems.RED_CANDY_CANE.value }, "Red Candy Cane")
        this.addItem({ ModItems.GREEN_CANDY_CANE.value }, "Green Candy Cane")
        this.addItem({ ModItems.WHITE_RED_CANDY_CANE.value }, "White-Red Candy Cane")
        this.addItem({ ModItems.WHITE_GREEN_CANDY_CANE.value }, "White-Green Candy Cane")
        this.addItem({ ModItems.RED_GREEN_CANDY_CANE.value }, "Red-Green Candy Cane")
        this.addItem({ ModItems.MILK_CHOCOLATE_BAR.value }, "Milk Chocolate")
        this.addItem({ ModItems.WHITE_CHOCOLATE_BAR.value }, "White Chocolate")
        this.addItem({ ModItems.DARK_CHOCOLATE_BAR.value }, "Dark Chocolate")
        this.addItem({ ModItems.MILK_CHOCOLATE_EGG.value }, "Milk Chocolate Egg")
        this.addItem({ ModItems.WHITE_CHOCOLATE_EGG.value }, "White Chocolate Egg")
        this.addItem({ ModItems.DARK_CHOCOLATE_EGG.value }, "Dark Chocolate Egg")
        this.addItem({ ModItems.MILK_BROWNIE.value }, "Milk Brownie")
        this.addItem({ ModItems.WHITE_BROWNIE.value }, "White Brownie")
        this.addItem({ ModItems.DARK_BROWNIE.value }, "Dark Brownie")
        this.addItem({ ModItems.WAFER_STICK.value }, "Wafer Stick")
        this.addItem({ ModItems.SUGAR_CRYSTAL.value }, "Sugar Crystal")
        this.addItem({ ModItems.RED_GUMMY.value }, "Lump of Red Gummy")
        this.addItem({ ModItems.ORANGE_GUMMY.value }, "Lump of Orange Gummy")
        this.addItem({ ModItems.YELLOW_GUMMY.value }, "Lump of Yellow Gummy")
        this.addItem({ ModItems.WHITE_GUMMY.value }, "Lump of White Gummy")
        this.addItem({ ModItems.GREEN_GUMMY.value }, "Lump of Green Gummy")
        this.addItem({ ModItems.RED_GUMMY_WORM.value }, "Red Gummy Worm")
        this.addItem({ ModItems.ORANGE_GUMMY_WORM.value }, "Orange Gummy Worm")
        this.addItem({ ModItems.YELLOW_GUMMY_WORM.value }, "Yellow Gummy Worm")
        this.addItem({ ModItems.WHITE_GUMMY_WORM.value }, "White Gummy Worm")
        this.addItem({ ModItems.GREEN_GUMMY_WORM.value }, "Green Gummy Worm")
        this.addItem({ ModItems.TELEPORTER.value }, "Magic Piece of Candy")
        this.addItem({ ModItems.MILK_CHOCOLATE_PICKAXE.value }, "Milk Chocolate Pickaxe")
        this.addItem({ ModItems.DARK_CHOCOLATE_PICKAXE.value }, "Dark Chocolate Pickaxe")
        this.addItem({ ModItems.WHITE_CHOCOLATE_PICKAXE.value }, "White Chocolate Pickaxe")
        this.addItem({ ModItems.MILK_CHOCOLATE_AXE.value }, "Milk Chocolate Axe")
        this.addItem({ ModItems.DARK_CHOCOLATE_AXE.value }, "Dark Chocolate Axe")
        this.addItem({ ModItems.WHITE_CHOCOLATE_AXE.value }, "White Chocolate Axe")
        this.addItem({ ModItems.MILK_CHOCOLATE_SHOVEL.value }, "Milk Chocolate Shovel")
        this.addItem({ ModItems.DARK_CHOCOLATE_SHOVEL.value }, "Dark Chocolate Shovel")
        this.addItem({ ModItems.WHITE_CHOCOLATE_SHOVEL.value }, "White Chocolate Shovel")
        this.addItem({ ModItems.MILK_CHOCOLATE_SWORD.value }, "Milk Chocolate Sword")
        this.addItem({ ModItems.DARK_CHOCOLATE_SWORD.value }, "Dark Chocolate Sword")
        this.addItem({ ModItems.WHITE_CHOCOLATE_SWORD.value }, "White Chocolate Sword")
        this.addItem({ ModItems.COTTON_CANDY_PICKAXE.value }, "Cotton Candy Pickaxe")
        this.addItem({ ModItems.COTTON_CANDY_AXE.value }, "Cotton Candy Axe")
        this.addItem({ ModItems.COTTON_CANDY_SHOVEL.value }, "Cotton Candy Shovel")
        this.addItem({ ModItems.COTTON_CANDY_SWORD.value }, "Cotton Candy Sword")
        this.addItem({ ModItems.LIQUID_CHOCOLATE_BUCKET.value }, "Liquid Chocolate Bucket")
        this.addItem({ ModItems.LIQUID_CANDY_BUCKET.value }, "Liquid Candy Bucket")

        this.addItem({ ModItems.COTTON_CANDY_SHEEP_SPAWN_EGG.value }, "Cotton Candy Sheep Spawn Egg")
        this.addItem({ ModItems.EASTER_CHICKEN_SPAWN_EGG.value }, "Easter Chicken Spawn Egg")
        this.addItem({ ModItems.GUMMY_MOUSE_SPAWN_EGG.value }, "Gummy Mouse Spawn Egg")
        this.addItem({ ModItems.GUMMY_BEAR_SPAWN_EGG.value }, "Gummy Bear Spawn Egg")

        this.addFluid(ModFluids.LIQUID_CHOCOLATE_SOURCE, "Liquid Chocolate")
        this.addFluid(ModFluids.LIQUID_CANDY_SOURCE, "Liquid Candy")

        this.addEntityType({ ModEntities.COTTON_CANDY_SHEEP.value }, "Cotton Candy Sheep")
        this.addEntityType({ ModEntities.EASTER_CHICKEN.value }, "Easter Chicken")
        this.addEntityType({ ModEntities.GUMMY_MOUSE.value }, "Gummy Mouse")
        this.addEntityType({ ModEntities.GUMMY_BEAR.value }, "Gummy Bear")

        this.add("itemGroup.candyworld.items", "Candy World - Items")
        this.add("itemGroup.candyworld.blocks", "Candy World - Blocks")
        this.add("itemGroup.candyworld.tools", "Candy World - Tools")

        this.add("biome.candyworld.gummy_swamp", "Gummy Swamp")
        this.add("biome.candyworld.chocolate_forest", "Chocolate Forest")
        this.add("biome.candyworld.cotton_candy_plains", "Cotton Candy Plains")
    }


    private fun addFluid(fluid: RegistryObject<out FlowingFluid>, name: String) {
        this.add("fluid.${CandyWorld.MOD_ID}.${fluid.path}", name)
    }
}